title = "Personal Website"
summary = "A personal website that auto populates information from parsing CV and Github Repos"
status = "Completed"
technologies = ["Rust", "Leptos", "WebAssembly", "GitHub Actions"]
highlights = [
  "Full auto parsing of CV pulled from Github Repo and auto populated into static webpage.",
  "Project based parsing of custom format for project info auto populated into website.",
  "Automated deployment of website to Cloudflare pages using Github Actions.",
  "Source of truth for project information is the CV and Github Repos, no need to manually update website.",
]
show_repository = true
