use std::fmt::Write;

use super::NormalizedProject;

/// Generates deterministic, borrowed Rust data for the website runtime.
#[must_use]
pub fn generate_projects_module(projects: &[NormalizedProject]) -> Vec<u8> {
    let mut output = String::from(
        "//! @generated by `sync-projects`; do not edit by hand.\n\n\
         use crate::projects::{Project, ProjectVisibility};\n\n\
         /// Selected projects generated from the configured GitHub repositories.\n\
         pub const PROJECTS: &[Project] = &[\n",
    );
    for project in projects {
        writeln!(output, "    Project {{").expect("writing to a string cannot fail");
        field(&mut output, "id", &project.id);
        field(&mut output, "repository", &project.repository);
        field(&mut output, "title", &project.title);
        field(&mut output, "summary", &project.summary);
        writeln!(
            output,
            "        visibility: ProjectVisibility::{},",
            if project.private { "Private" } else { "Public" }
        )
        .expect("writing to a string cannot fail");
        field(
            &mut output,
            "project_date",
            project
                .portfolio_date
                .as_ref()
                .unwrap_or(&project.created_date),
        );
        option_field(&mut output, "status", project.status.as_deref());
        slice_field(&mut output, "technologies", &project.technologies);
        slice_field(&mut output, "highlights", &project.highlights);
        field(&mut output, "image_url", &project.image_url);
        option_field(
            &mut output,
            "repository_url",
            project.repository_url.as_deref(),
        );
        option_field(&mut output, "demo_url", project.demo_url.as_deref());
        output.push_str("    },\n");
    }
    output.push_str("];\n");
    output.into_bytes()
}

fn field(output: &mut String, name: &str, value: &str) {
    writeln!(output, "        {name}: {value:?},").expect("writing to a string cannot fail");
}

fn option_field(output: &mut String, name: &str, value: Option<&str>) {
    match value {
        Some(value) => writeln!(output, "        {name}: Some({value:?}),"),
        None => writeln!(output, "        {name}: None,"),
    }
    .expect("writing to a string cannot fail");
}

fn slice_field(output: &mut String, name: &str, values: &[String]) {
    if values.is_empty() {
        writeln!(output, "        {name}: &[],").expect("writing to a string cannot fail");
        return;
    }

    let inline_values = values
        .iter()
        .map(|value| format!("{value:?}"))
        .collect::<Vec<_>>()
        .join(", ");
    let inline_field = format!("        {name}: &[{inline_values}],");

    // Keep a margin below rustfmt's wrapping limit so generated output stays
    // stable when a project contains a moderately long technology list.
    if inline_field.chars().count() <= 88 {
        writeln!(output, "{inline_field}").expect("writing to a string cannot fail");
        return;
    }

    writeln!(output, "        {name}: &[").expect("writing to a string cannot fail");
    for value in values {
        writeln!(output, "            {value:?},").expect("writing to a string cannot fail");
    }
    output.push_str("        ],\n");
}
