use std::{
    fs::{self, File, OpenOptions},
    io::Write,
    path::{Path, PathBuf},
};

use super::{GENERATED_PROJECTS_PATH, ProjectSyncError};

const LOCK_FILENAME: &str = ".project-sync.lock";

/// Atomic filesystem boundary for generated project data.
#[derive(Clone, Debug)]
pub struct ProjectDataStore {
    repository_root: PathBuf,
}

impl ProjectDataStore {
    #[must_use]
    pub fn new(repository_root: impl AsRef<Path>) -> Self {
        Self {
            repository_root: repository_root.as_ref().to_path_buf(),
        }
    }

    /// Atomically installs complete generated bytes and avoids unchanged writes.
    pub fn commit_if_changed(&self, generated: &[u8]) -> Result<bool, ProjectSyncError> {
        if generated.is_empty() || std::str::from_utf8(generated).is_err() {
            return Err(ProjectSyncError::Validation(
                "generated project module must be non-empty UTF-8".to_owned(),
            ));
        }
        let target = self.repository_root.join(GENERATED_PROJECTS_PATH);
        match fs::read(&target) {
            Ok(current) if current == generated => return Ok(false),
            Ok(_) => {}
            Err(error) if error.kind() == std::io::ErrorKind::NotFound => {}
            Err(error) => {
                return Err(ProjectSyncError::Local(format!(
                    "could not read {}: {error}",
                    target.display()
                )));
            }
        }
        let parent = target
            .parent()
            .expect("generated project path has a parent");
        fs::create_dir_all(parent).map_err(|error| {
            ProjectSyncError::Local(format!("could not create {}: {error}", parent.display()))
        })?;
        let lock = self.repository_root.join(LOCK_FILENAME);
        let _guard = LockGuard::acquire(lock)?;
        let mut staged = tempfile::NamedTempFile::new_in(parent).map_err(|error| {
            ProjectSyncError::Local(format!("could not stage project data: {error}"))
        })?;
        staged.write_all(generated).map_err(|error| {
            ProjectSyncError::Local(format!("could not write staged project data: {error}"))
        })?;
        staged.as_file().sync_all().map_err(|error| {
            ProjectSyncError::Local(format!("could not sync staged project data: {error}"))
        })?;

        let backup = parent.join(".generated-projects.backup");
        let had_target = target.exists();
        if had_target {
            fs::rename(&target, &backup).map_err(|error| {
                ProjectSyncError::Local(format!("could not back up {}: {error}", target.display()))
            })?;
        }
        if let Err(error) = staged.persist(&target) {
            if had_target {
                let _ = fs::rename(&backup, &target);
            }
            return Err(ProjectSyncError::Local(format!(
                "could not install {}: {}",
                target.display(),
                error.error
            )));
        }
        if had_target {
            fs::remove_file(&backup).map_err(|error| {
                ProjectSyncError::Local(format!(
                    "installed project data but could not remove backup {}: {error}",
                    backup.display()
                ))
            })?;
        }
        Ok(true)
    }
}

struct LockGuard {
    path: PathBuf,
    _file: File,
}

impl LockGuard {
    fn acquire(path: PathBuf) -> Result<Self, ProjectSyncError> {
        let file = OpenOptions::new()
            .write(true)
            .create_new(true)
            .open(&path)
            .map_err(|error| {
                ProjectSyncError::Local(format!(
                    "could not acquire project synchronization lock {}: {error}",
                    path.display()
                ))
            })?;
        Ok(Self { path, _file: file })
    }
}

impl Drop for LockGuard {
    fn drop(&mut self) {
        let _ = fs::remove_file(&self.path);
    }
}
