use crate::cv::{
    Cv, CvDate, DateRange, DateRangeEnd, Inline, Location, Month, RichText, SocialPlatform,
};

use super::RemoteTag;

/// Generates the static Rust module consumed by the website crate.
///
/// The output is deterministic for a domain value and source identity. It uses
/// borrowed `Cow` values, so including the generated module requires no runtime
/// deserialization or content allocation.
#[must_use]
pub fn generate_cv_module(cv: &Cv<'_>, source: &RemoteTag) -> Vec<u8> {
    let mut writer = RustWriter::default();
    writer.line("// @generated by the Stage 2 CV importer; do not edit.");
    writer.line("");
    writer.line("use std::borrow::Cow;");
    writer.line("");
    writer.line("use crate::cv::{");
    writer.indented(|writer| {
        writer.line(
            "ContactDetails, Cv, CvDate, DateRange, DateRangeEnd, Education, Experience, Inline, Location,",
        );
        writer.line("Month, Profile, Project, RichText, SkillGroup, SocialLink, SocialPlatform,");
    });
    writer.line("};");
    writer.line("");
    writer.line(&format!(
        "/// Upstream semantic tag used to generate [`CV`].\npub const SOURCE_TAG: &str = {:?};",
        source.name
    ));
    writer.line(&format!(
        "/// Immutable upstream commit used to generate [`CV`].\npub const SOURCE_COMMIT_SHA: &str = {:?};",
        source.commit_sha
    ));
    writer.line("");
    writer.line("/// CV data validated and generated from the synchronized LaTeX source.");
    writer.line("#[rustfmt::skip]");
    writer.line("pub static CV: Cv<'static> = Cv {");
    writer.indented(|writer| write_cv(writer, cv));
    writer.line("};");
    writer.output.into_bytes()
}

fn write_cv(writer: &mut RustWriter, cv: &Cv<'_>) {
    writer.line("profile: Profile {");
    writer.indented(|writer| {
        writer.field_cow("full_name", &cv.profile.full_name);
        writer.line("contact: ContactDetails {");
        writer.indented(|writer| writer.field_cow("email", &cv.profile.contact.email));
        writer.line("},");
        writer.line("social_links: Cow::Borrowed(&[");
        writer.indented(|writer| {
            for link in cv.profile.social_links.iter() {
                writer.line("SocialLink {");
                writer.indented(|writer| {
                    let platform = match link.platform {
                        SocialPlatform::GitHub => "SocialPlatform::GitHub",
                        SocialPlatform::LinkedIn => "SocialPlatform::LinkedIn",
                    };
                    writer.line(&format!("platform: {platform},"));
                    writer.field_cow("url", &link.url);
                    writer.line("label: RichText {");
                    writer.indented(|writer| write_rich_nodes(writer, &link.label));
                    writer.line("},");
                });
                writer.line("},");
            }
        });
        writer.line("]),");
    });
    writer.line("},");

    writer.line("education: Cow::Borrowed(&[");
    writer.indented(|writer| {
        for entry in cv.education.iter() {
            writer.line("Education {");
            writer.indented(|writer| {
                writer.rich_field("institution", &entry.institution);
                writer.rich_field("qualification", &entry.qualification);
                write_location_field(writer, &entry.location);
                write_date_range_field(writer, entry.dates);
            });
            writer.line("},");
        }
    });
    writer.line("]),");

    writer.line("experience: Cow::Borrowed(&[");
    writer.indented(|writer| {
        for entry in cv.experience.iter() {
            writer.line("Experience {");
            writer.indented(|writer| {
                writer.rich_field("role", &entry.role);
                writer.rich_field("organisation", &entry.organisation);
                write_location_field(writer, &entry.location);
                write_date_range_field(writer, entry.dates);
                writer.rich_slice_field("highlights", &entry.highlights);
            });
            writer.line("},");
        }
    });
    writer.line("]),");

    writer.line("projects: Cow::Borrowed(&[");
    writer.indented(|writer| {
        for project in cv.projects.iter() {
            writer.line("Project {");
            writer.indented(|writer| {
                writer.rich_field("title", &project.title);
                writer.cow_slice_field("technologies", &project.technologies);
                match &project.period {
                    Some(period) => {
                        writer.line("period: Some(RichText {");
                        writer.indented(|writer| write_rich_nodes(writer, period));
                        writer.line("}),");
                    }
                    None => writer.line("period: None,"),
                }
                writer.rich_slice_field("highlights", &project.highlights);
            });
            writer.line("},");
        }
    });
    writer.line("]),");

    writer.line("skills: Cow::Borrowed(&[");
    writer.indented(|writer| {
        for group in cv.skills.iter() {
            writer.line("SkillGroup {");
            writer.indented(|writer| {
                writer.field_cow("category", &group.category);
                writer.cow_slice_field("skills", &group.skills);
            });
            writer.line("},");
        }
    });
    writer.line("]),");
}

fn write_location_field(writer: &mut RustWriter, location: &Location<'_>) {
    writer.line("location: Location {");
    writer.indented(|writer| {
        writer.field_cow("city", &location.city);
        writer.field_cow("country", &location.country);
    });
    writer.line("},");
}

fn write_date_range_field(writer: &mut RustWriter, dates: DateRange) {
    writer.line("dates: DateRange {");
    writer.indented(|writer| {
        writer.line("start: CvDate {");
        writer.indented(|writer| write_date(writer, dates.start));
        writer.line("},");
        match dates.end {
            DateRangeEnd::Date(date) => {
                writer.line("end: DateRangeEnd::Date(CvDate {");
                writer.indented(|writer| write_date(writer, date));
                writer.line("}),");
            }
            DateRangeEnd::Present => writer.line("end: DateRangeEnd::Present,"),
        }
    });
    writer.line("},");
}

fn write_date(writer: &mut RustWriter, date: CvDate) {
    writer.line(&format!("year: {},", date.year));
    let month = match date.month {
        Month::January => "Month::January",
        Month::February => "Month::February",
        Month::March => "Month::March",
        Month::April => "Month::April",
        Month::May => "Month::May",
        Month::June => "Month::June",
        Month::July => "Month::July",
        Month::August => "Month::August",
        Month::September => "Month::September",
        Month::October => "Month::October",
        Month::November => "Month::November",
        Month::December => "Month::December",
    };
    writer.line(&format!("month: {month},"));
}

fn write_rich_nodes(writer: &mut RustWriter, rich: &RichText<'_>) {
    writer.line("nodes: Cow::Borrowed(&[");
    writer.indented(|writer| {
        for node in rich.nodes.iter() {
            write_inline(writer, node);
        }
    });
    writer.line("]),");
}

fn write_inline(writer: &mut RustWriter, inline: &Inline<'_>) {
    match inline {
        Inline::Text(text) => writer.line(&format!("Inline::Text(Cow::Borrowed({text:?})),")),
        Inline::Strong(content) => {
            writer.line("Inline::Strong(RichText {");
            writer.indented(|writer| write_rich_nodes(writer, content));
            writer.line("}),");
        }
        Inline::Emphasis(content) => {
            writer.line("Inline::Emphasis(RichText {");
            writer.indented(|writer| write_rich_nodes(writer, content));
            writer.line("}),");
        }
        Inline::Underline(content) => {
            writer.line("Inline::Underline(RichText {");
            writer.indented(|writer| write_rich_nodes(writer, content));
            writer.line("}),");
        }
        Inline::Link { target, label } => {
            writer.line("Inline::Link {");
            writer.indented(|writer| {
                writer.line(&format!("target: Cow::Borrowed({target:?}),"));
                writer.line("label: RichText {");
                writer.indented(|writer| write_rich_nodes(writer, label));
                writer.line("},");
            });
            writer.line("},");
        }
    }
}

#[derive(Default)]
struct RustWriter {
    output: String,
    indentation: usize,
}

impl RustWriter {
    fn line(&mut self, line: &str) {
        for (index, line) in line.lines().enumerate() {
            if index > 0 {
                self.output.push('\n');
            }
            for _ in 0..self.indentation {
                self.output.push_str("    ");
            }
            self.output.push_str(line);
        }
        self.output.push('\n');
    }

    fn indented(&mut self, callback: impl FnOnce(&mut Self)) {
        self.indentation += 1;
        callback(self);
        self.indentation -= 1;
    }

    fn field_cow(&mut self, field: &str, value: &str) {
        self.line(&format!("{field}: Cow::Borrowed({value:?}),"));
    }

    fn rich_field(&mut self, field: &str, value: &RichText<'_>) {
        self.line(&format!("{field}: RichText {{"));
        self.indented(|writer| write_rich_nodes(writer, value));
        self.line("},");
    }

    fn rich_slice_field(&mut self, field: &str, values: &[RichText<'_>]) {
        self.line(&format!("{field}: Cow::Borrowed(&["));
        self.indented(|writer| {
            for value in values {
                writer.line("RichText {");
                writer.indented(|writer| write_rich_nodes(writer, value));
                writer.line("},");
            }
        });
        self.line("]),");
    }

    fn cow_slice_field(&mut self, field: &str, values: &[impl AsRef<str>]) {
        self.line(&format!("{field}: Cow::Borrowed(&["));
        self.indented(|writer| {
            for value in values {
                let value = value.as_ref();
                writer.line(&format!("Cow::Borrowed({value:?}),"));
            }
        });
        self.line("]),");
    }
}
