// @generated by the Stage 2 CV importer; do not edit.

use std::borrow::Cow;

use crate::cv::{
    ContactDetails, Cv, CvDate, DateRange, DateRangeEnd, Education, Experience, Inline, Location,
    Month, Profile, Project, RichText, SkillGroup, SocialLink, SocialPlatform,
};

/// Upstream semantic tag used to generate [`CV`].
pub const SOURCE_TAG: &str = "v1.0.0";
/// Immutable upstream commit used to generate [`CV`].
pub const SOURCE_COMMIT_SHA: &str = "5c689c5fc89c9121a00ff2260dd48d2feef6c0ac";

/// CV data validated and generated from the synchronized LaTeX source.
#[rustfmt::skip]
pub static CV: Cv<'static> = Cv {
    profile: Profile {
        full_name: Cow::Borrowed("Hayden Farrell"),
        contact: ContactDetails {
            email: Cow::Borrowed("haydenfarrell@outlook.com"),
        },
        social_links: Cow::Borrowed(&[
            SocialLink {
                platform: SocialPlatform::LinkedIn,
                url: Cow::Borrowed("https://linkedin.com/in/..."),
                label: RichText {
                    nodes: Cow::Borrowed(&[
                        Inline::Underline(RichText {
                            nodes: Cow::Borrowed(&[
                                Inline::Text(Cow::Borrowed("linkedin/haydenfarrell")),
                            ]),
                        }),
                    ]),
                },
            },
            SocialLink {
                platform: SocialPlatform::GitHub,
                url: Cow::Borrowed("https://github.com/osdesa"),
                label: RichText {
                    nodes: Cow::Borrowed(&[
                        Inline::Underline(RichText {
                            nodes: Cow::Borrowed(&[
                                Inline::Text(Cow::Borrowed("github.com/osdesa")),
                            ]),
                        }),
                    ]),
                },
            },
        ]),
    },
    education: Cow::Borrowed(&[
        Education {
            institution: RichText {
                nodes: Cow::Borrowed(&[
                    Inline::Text(Cow::Borrowed("University of Nottingham")),
                ]),
            },
            qualification: RichText {
                nodes: Cow::Borrowed(&[
                    Inline::Text(Cow::Borrowed("BSc Computer Science with a Year in Industry (Predicted First-Class Honours)")),
                ]),
            },
            location: Location {
                city: Cow::Borrowed("Nottingham"),
                country: Cow::Borrowed("UK"),
            },
            dates: DateRange {
                start: CvDate {
                    year: 2023,
                    month: Month::August,
                },
                end: DateRangeEnd::Date(CvDate {
                    year: 2027,
                    month: Month::May,
                }),
            },
        },
        Education {
            institution: RichText {
                nodes: Cow::Borrowed(&[
                    Inline::Text(Cow::Borrowed("Aquinas College")),
                ]),
            },
            qualification: RichText {
                nodes: Cow::Borrowed(&[
                    Inline::Text(Cow::Borrowed("Mathematics (A), Computer Science (A), Further Mathematics (A)")),
                ]),
            },
            location: Location {
                city: Cow::Borrowed("Manchester"),
                country: Cow::Borrowed("UK"),
            },
            dates: DateRange {
                start: CvDate {
                    year: 2021,
                    month: Month::August,
                },
                end: DateRangeEnd::Date(CvDate {
                    year: 2023,
                    month: Month::May,
                }),
            },
        },
    ]),
    experience: Cow::Borrowed(&[
        Experience {
            role: RichText {
                nodes: Cow::Borrowed(&[
                    Inline::Text(Cow::Borrowed("Software Engineer part time")),
                ]),
            },
            organisation: RichText {
                nodes: Cow::Borrowed(&[
                    Inline::Text(Cow::Borrowed("Leonardo UK")),
                ]),
            },
            location: Location {
                city: Cow::Borrowed("Newcastle upon Tyne"),
                country: Cow::Borrowed("UK"),
            },
            dates: DateRange {
                start: CvDate {
                    year: 2026,
                    month: Month::July,
                },
                end: DateRangeEnd::Present,
            },
            highlights: Cow::Borrowed(&[
                RichText {
                    nodes: Cow::Borrowed(&[
                        Inline::Text(Cow::Borrowed("One of only three undergraduate software engineers offered a part-time role while returning to university")),
                    ]),
                },
                RichText {
                    nodes: Cow::Borrowed(&[
                        Inline::Text(Cow::Borrowed("Developing safety-critical real-time software remotely as part of an Agile engineering team while completing my degree")),
                    ]),
                },
                RichText {
                    nodes: Cow::Borrowed(&[
                        Inline::Text(Cow::Borrowed("Balancing both university and work commitments to ensure deadlines are met")),
                    ]),
                },
                RichText {
                    nodes: Cow::Borrowed(&[
                        Inline::Text(Cow::Borrowed("Maintain and monitor Jenkins CI pipelines to ensure reliable build and test execution alongside ongoing software development.")),
                    ]),
                },
            ]),
        },
        Experience {
            role: RichText {
                nodes: Cow::Borrowed(&[
                    Inline::Text(Cow::Borrowed("Industrial Placement Software Engineer")),
                ]),
            },
            organisation: RichText {
                nodes: Cow::Borrowed(&[
                    Inline::Text(Cow::Borrowed("Leonardo UK")),
                ]),
            },
            location: Location {
                city: Cow::Borrowed("Newcastle upon Tyne"),
                country: Cow::Borrowed("UK"),
            },
            dates: DateRange {
                start: CvDate {
                    year: 2025,
                    month: Month::June,
                },
                end: DateRangeEnd::Date(CvDate {
                    year: 2026,
                    month: Month::July,
                }),
            },
            highlights: Cow::Borrowed(&[
                RichText {
                    nodes: Cow::Borrowed(&[
                        Inline::Text(Cow::Borrowed("Developed and maintained safety-critical real-time software within an Agile engineering team following DO-178C development practices")),
                    ]),
                },
                RichText {
                    nodes: Cow::Borrowed(&[
                        Inline::Text(Cow::Borrowed("Led the design and implementation of a synthetic testing framework in C++ for complex embedded software, reducing dependency on hardware integration during development.")),
                    ]),
                },
                RichText {
                    nodes: Cow::Borrowed(&[
                        Inline::Text(Cow::Borrowed("Led design workshops with over 10 engineers including principal and lead software engineers to get stakeholder requirements and feedback on software design")),
                    ]),
                },
                RichText {
                    nodes: Cow::Borrowed(&[
                        Inline::Text(Cow::Borrowed("Developed a custom test application used by over 10 engineers across teams to allow for quick developer testing of a complex engineering system")),
                    ]),
                },
                RichText {
                    nodes: Cow::Borrowed(&[
                        Inline::Text(Cow::Borrowed("Created a custom tool to allow the visualisation of large amounts of realtime mathematical data to allow for quick analysis of complex engineering systems")),
                    ]),
                },
            ]),
        },
    ]),
    projects: Cow::Borrowed(&[
        Project {
            title: RichText {
                nodes: Cow::Borrowed(&[
                    Inline::Strong(RichText {
                        nodes: Cow::Borrowed(&[
                            Inline::Text(Cow::Borrowed("Atlas")),
                        ]),
                    }),
                ]),
            },
            technologies: Cow::Borrowed(&[
                Cow::Borrowed("C++"),
                Cow::Borrowed("Vulkan"),
                Cow::Borrowed("CMake"),
                Cow::Borrowed("Python"),
            ]),
            period: Some(RichText {
                nodes: Cow::Borrowed(&[
                    Inline::Text(Cow::Borrowed("Current Project")),
                ]),
            }),
            highlights: Cow::Borrowed(&[
                RichText {
                    nodes: Cow::Borrowed(&[
                        Inline::Text(Cow::Borrowed("Developing a user-space heterogeneous task scheduler supporting CPU workloads and preemptive-style GPU scheduling through cooperative execution slices using Vulkan.")),
                    ]),
                },
                RichText {
                    nodes: Cow::Borrowed(&[
                        Inline::Text(Cow::Borrowed("Designed and implemented multiple scheduling policies, including FIFO, priority-based and round-robin, with benchmarking to evaluate latency, throughput and fairness")),
                    ]),
                },
                RichText {
                    nodes: Cow::Borrowed(&[
                        Inline::Text(Cow::Borrowed("Built a Vulkan compute backend enabling fine-grained control over GPU work submission, profiling execution using timeline visualisation and performance metrics")),
                    ]),
                },
                RichText {
                    nodes: Cow::Borrowed(&[
                        Inline::Text(Cow::Borrowed("Built an automated benchmarking framework to evaluate scheduling overhead and performance across different workloads, including CPU-bound, GPU-bound and mixed workloads")),
                    ]),
                },
            ]),
        },
        Project {
            title: RichText {
                nodes: Cow::Borrowed(&[
                    Inline::Strong(RichText {
                        nodes: Cow::Borrowed(&[
                            Inline::Link {
                                target: Cow::Borrowed("https://github.com/osdesa/Blocky"),
                                label: RichText {
                                    nodes: Cow::Borrowed(&[
                                        Inline::Underline(RichText {
                                            nodes: Cow::Borrowed(&[
                                                Inline::Text(Cow::Borrowed("Blocky")),
                                            ]),
                                        }),
                                    ]),
                                },
                            },
                        ]),
                    }),
                ]),
            },
            technologies: Cow::Borrowed(&[
                Cow::Borrowed("C++"),
                Cow::Borrowed("OpenGL"),
                Cow::Borrowed("GLSL"),
                Cow::Borrowed("Python"),
                Cow::Borrowed("CMake"),
            ]),
            period: None,
            highlights: Cow::Borrowed(&[
                RichText {
                    nodes: Cow::Borrowed(&[
                        Inline::Text(Cow::Borrowed("Developed a voxel-based 3D game engine in C++ using OpenGL and GLSL")),
                    ]),
                },
                RichText {
                    nodes: Cow::Borrowed(&[
                        Inline::Text(Cow::Borrowed("Achieved a stable 60 FPS while rendering over 100,000 voxels with real-time lighting")),
                    ]),
                },
                RichText {
                    nodes: Cow::Borrowed(&[
                        Inline::Text(Cow::Borrowed("Created a custom linear algebra library to support vector and matrix mathematics required for 3D graphics")),
                    ]),
                },
            ]),
        },
    ]),
    skills: Cow::Borrowed(&[
        SkillGroup {
            category: Cow::Borrowed("Languages"),
            skills: Cow::Borrowed(&[
                Cow::Borrowed("C++"),
                Cow::Borrowed("C"),
                Cow::Borrowed("Python"),
                Cow::Borrowed("Java"),
                Cow::Borrowed("Matlab"),
                Cow::Borrowed("VHDL"),
                Cow::Borrowed("ARM"),
                Cow::Borrowed("Rust"),
                Cow::Borrowed("Shell Scripting"),
                Cow::Borrowed("CMake"),
            ]),
        },
        SkillGroup {
            category: Cow::Borrowed("Libraries"),
            skills: Cow::Borrowed(&[
                Cow::Borrowed("OpenGL"),
                Cow::Borrowed("Vulkan"),
                Cow::Borrowed("Flask"),
            ]),
        },
        SkillGroup {
            category: Cow::Borrowed("Tools"),
            skills: Cow::Borrowed(&[
                Cow::Borrowed("Git"),
                Cow::Borrowed("Docker"),
                Cow::Borrowed("VS Code"),
                Cow::Borrowed("Visual Studio"),
                Cow::Borrowed("IntelliJ"),
                Cow::Borrowed("Jenkins"),
                Cow::Borrowed("MISRA"),
                Cow::Borrowed("PolySpace"),
            ]),
        },
        SkillGroup {
            category: Cow::Borrowed("Training/Certificates"),
            skills: Cow::Borrowed(&[
                Cow::Borrowed("DO-178C Certified"),
                Cow::Borrowed("C++ Training"),
            ]),
        },
        SkillGroup {
            category: Cow::Borrowed("Hobbies"),
            skills: Cow::Borrowed(&[
                Cow::Borrowed("Climbing/Bouldering"),
                Cow::Borrowed("Leadership"),
                Cow::Borrowed("Drones"),
            ]),
        },
    ]),
};
