// @generated by the Stage 2 CV importer; do not edit.

use std::borrow::Cow;

use crate::cv::{
    ContactDetails, Cv, CvDate, DateRange, DateRangeEnd, Education, Experience, Inline, Location,
    Month, Profile, ProfileWebsite, Project, RichText, SkillGroup, SocialLink, SocialPlatform,
};

/// Upstream semantic tag used to generate [`CV`].
pub const SOURCE_TAG: &str = "v1.1.0";
/// Immutable upstream commit used to generate [`CV`].
pub const SOURCE_COMMIT_SHA: &str = "9af13c8a6b533acaf77b39bd4d5a4c62918e80bc";

/// CV data validated and generated from the synchronized LaTeX source.
#[rustfmt::skip]
pub static CV: Cv<'static> = Cv {
    profile: Profile {
        full_name: Cow::Borrowed("Hayden Farrell"),
        contact: ContactDetails {
            email: Cow::Borrowed("haydenfarrell@outlook.com"),
        },
        social_links: Cow::Borrowed(&[
            SocialLink {
                platform: SocialPlatform::LinkedIn,
                url: Cow::Borrowed("https://www.linkedin.com/in/haydenfarrell1/"),
                label: RichText {
                    nodes: Cow::Borrowed(&[
                        Inline::Underline(RichText {
                            nodes: Cow::Borrowed(&[
                                Inline::Text(Cow::Borrowed("linkedin")),
                            ]),
                        }),
                    ]),
                },
            },
            SocialLink {
                platform: SocialPlatform::GitHub,
                url: Cow::Borrowed("https://github.com/osdesa"),
                label: RichText {
                    nodes: Cow::Borrowed(&[
                        Inline::Underline(RichText {
                            nodes: Cow::Borrowed(&[
                                Inline::Text(Cow::Borrowed("github")),
                            ]),
                        }),
                    ]),
                },
            },
        ]),
        website: Some(ProfileWebsite {
            url: Cow::Borrowed("https://haydenfarrell.dev/"),
            label: RichText {
                nodes: Cow::Borrowed(&[
                    Inline::Underline(RichText {
                        nodes: Cow::Borrowed(&[
                            Inline::Text(Cow::Borrowed("Website")),
                        ]),
                    }),
                ]),
            },
        }),
    },
    education: Cow::Borrowed(&[
        Education {
            institution: RichText {
                nodes: Cow::Borrowed(&[
                    Inline::Text(Cow::Borrowed("University of Nottingham")),
                ]),
            },
            qualification: RichText {
                nodes: Cow::Borrowed(&[
                    Inline::Text(Cow::Borrowed("BSc Computer Science with a Year in Industry (Predicted First-Class Honours avg. 75%)")),
                ]),
            },
            location: Location {
                city: Cow::Borrowed("Nottingham"),
                country: Cow::Borrowed("UK"),
            },
            dates: DateRange {
                start: CvDate {
                    year: 2023,
                    month: Month::August,
                },
                end: DateRangeEnd::Date(CvDate {
                    year: 2027,
                    month: Month::May,
                }),
            },
        },
        Education {
            institution: RichText {
                nodes: Cow::Borrowed(&[
                    Inline::Text(Cow::Borrowed("Aquinas College")),
                ]),
            },
            qualification: RichText {
                nodes: Cow::Borrowed(&[
                    Inline::Text(Cow::Borrowed("Mathematics (A), Computer Science (A), Further Mathematics (A)")),
                ]),
            },
            location: Location {
                city: Cow::Borrowed("Manchester"),
                country: Cow::Borrowed("UK"),
            },
            dates: DateRange {
                start: CvDate {
                    year: 2021,
                    month: Month::August,
                },
                end: DateRangeEnd::Date(CvDate {
                    year: 2023,
                    month: Month::May,
                }),
            },
        },
    ]),
    experience: Cow::Borrowed(&[
        Experience {
            role: RichText {
                nodes: Cow::Borrowed(&[
                    Inline::Text(Cow::Borrowed("Part-Time Software Engineer")),
                ]),
            },
            organisation: RichText {
                nodes: Cow::Borrowed(&[
                    Inline::Text(Cow::Borrowed("Leonardo UK")),
                ]),
            },
            location: Location {
                city: Cow::Borrowed("Newcastle upon Tyne"),
                country: Cow::Borrowed("UK"),
            },
            dates: DateRange {
                start: CvDate {
                    year: 2026,
                    month: Month::July,
                },
                end: DateRangeEnd::Present,
            },
            highlights: Cow::Borrowed(&[
                RichText {
                    nodes: Cow::Borrowed(&[
                        Inline::Text(Cow::Borrowed("Selected as one of three undergraduate software engineers to continue at Leonardo part-time while completing my degree")),
                    ]),
                },
                RichText {
                    nodes: Cow::Borrowed(&[
                        Inline::Text(Cow::Borrowed("Develop safety-critical, real-time software remotely within an Agile engineering team alongside full-time university study")),
                    ]),
                },
                RichText {
                    nodes: Cow::Borrowed(&[
                        Inline::Text(Cow::Borrowed("Maintain and monitor Jenkins CI pipelines, supporting reliable automated build and test execution across ongoing development")),
                    ]),
                },
            ]),
        },
        Experience {
            role: RichText {
                nodes: Cow::Borrowed(&[
                    Inline::Text(Cow::Borrowed("Industrial Placement Software Engineer")),
                ]),
            },
            organisation: RichText {
                nodes: Cow::Borrowed(&[
                    Inline::Text(Cow::Borrowed("Leonardo UK")),
                ]),
            },
            location: Location {
                city: Cow::Borrowed("Newcastle upon Tyne"),
                country: Cow::Borrowed("UK"),
            },
            dates: DateRange {
                start: CvDate {
                    year: 2025,
                    month: Month::June,
                },
                end: DateRangeEnd::Date(CvDate {
                    year: 2026,
                    month: Month::July,
                }),
            },
            highlights: Cow::Borrowed(&[
                RichText {
                    nodes: Cow::Borrowed(&[
                        Inline::Text(Cow::Borrowed("Developed and maintained safety-critical, real-time embedded software within an Agile engineering team, following DO-178C development practices")),
                    ]),
                },
                RichText {
                    nodes: Cow::Borrowed(&[
                        Inline::Text(Cow::Borrowed("Led the design and implementation of a C++ synthetic testing framework, reducing integration time by over 50% and enabling significantly more accurate project time estimates")),
                    ]),
                },
                RichText {
                    nodes: Cow::Borrowed(&[
                        Inline::Text(Cow::Borrowed("Led requirements and design workshops with 10+ engineers, including principal and lead engineers, to gather stakeholder needs and refine the software design")),
                    ]),
                },
                RichText {
                    nodes: Cow::Borrowed(&[
                        Inline::Text(Cow::Borrowed("Built a custom test application adopted by 30+ engineers across teams, enabling hardware-in-the-loop testing of complex systems")),
                    ]),
                },
                RichText {
                    nodes: Cow::Borrowed(&[
                        Inline::Text(Cow::Borrowed("Created a tool to visualise ultra-high-volume, real-time IQ data, enabling analysis of end to end system behaviour")),
                    ]),
                },
            ]),
        },
    ]),
    projects: Cow::Borrowed(&[
        Project {
            title: RichText {
                nodes: Cow::Borrowed(&[
                    Inline::Strong(RichText {
                        nodes: Cow::Borrowed(&[
                            Inline::Link {
                                target: Cow::Borrowed("https://github.com/osdesa/Atlas"),
                                label: RichText {
                                    nodes: Cow::Borrowed(&[
                                        Inline::Underline(RichText {
                                            nodes: Cow::Borrowed(&[
                                                Inline::Text(Cow::Borrowed("Atlas")),
                                            ]),
                                        }),
                                    ]),
                                },
                            },
                        ]),
                    }),
                ]),
            },
            technologies: Cow::Borrowed(&[
                Cow::Borrowed("C++"),
                Cow::Borrowed("Vulkan"),
                Cow::Borrowed("CMake"),
                Cow::Borrowed("Python"),
            ]),
            period: Some(RichText {
                nodes: Cow::Borrowed(&[
                    Inline::Text(Cow::Borrowed("Current Project")),
                ]),
            }),
            highlights: Cow::Borrowed(&[
                RichText {
                    nodes: Cow::Borrowed(&[
                        Inline::Text(Cow::Borrowed("Developing a user-space heterogeneous task scheduler supporting CPU workloads and preemptive-style GPU scheduling through cooperative execution slices using Vulkan.")),
                    ]),
                },
                RichText {
                    nodes: Cow::Borrowed(&[
                        Inline::Text(Cow::Borrowed("Designed and implemented multiple scheduling policies, including FIFO, priority-based and round-robin, with benchmarking to evaluate latency, throughput and fairness")),
                    ]),
                },
                RichText {
                    nodes: Cow::Borrowed(&[
                        Inline::Text(Cow::Borrowed("Built a Vulkan compute backend enabling fine-grained control over GPU work submission, profiling execution using timeline visualisation and performance metrics")),
                    ]),
                },
                RichText {
                    nodes: Cow::Borrowed(&[
                        Inline::Text(Cow::Borrowed("Built an automated benchmarking framework to evaluate scheduling overhead and performance across different workloads, including CPU-bound, GPU-bound and mixed workloads")),
                    ]),
                },
            ]),
        },
        Project {
            title: RichText {
                nodes: Cow::Borrowed(&[
                    Inline::Strong(RichText {
                        nodes: Cow::Borrowed(&[
                            Inline::Link {
                                target: Cow::Borrowed("https://github.com/osdesa/Blocky"),
                                label: RichText {
                                    nodes: Cow::Borrowed(&[
                                        Inline::Underline(RichText {
                                            nodes: Cow::Borrowed(&[
                                                Inline::Text(Cow::Borrowed("Blocky")),
                                            ]),
                                        }),
                                    ]),
                                },
                            },
                        ]),
                    }),
                ]),
            },
            technologies: Cow::Borrowed(&[
                Cow::Borrowed("C++"),
                Cow::Borrowed("OpenGL"),
                Cow::Borrowed("GLSL"),
                Cow::Borrowed("Python"),
                Cow::Borrowed("CMake"),
            ]),
            period: Some(RichText {
                nodes: Cow::Borrowed(&[
                    Inline::Text(Cow::Borrowed("Oct. 2022 -- May 2023")),
                ]),
            }),
            highlights: Cow::Borrowed(&[
                RichText {
                    nodes: Cow::Borrowed(&[
                        Inline::Text(Cow::Borrowed("Developed a voxel-based 3D game engine in C++ using OpenGL and GLSL")),
                    ]),
                },
                RichText {
                    nodes: Cow::Borrowed(&[
                        Inline::Text(Cow::Borrowed("Achieved a stable 60 FPS while rendering over 100,000 voxels with real-time lighting")),
                    ]),
                },
                RichText {
                    nodes: Cow::Borrowed(&[
                        Inline::Text(Cow::Borrowed("Created a custom linear algebra library to support vector and matrix mathematics required for 3D graphics")),
                    ]),
                },
            ]),
        },
    ]),
    skills: Cow::Borrowed(&[
        SkillGroup {
            category: Cow::Borrowed("Languages"),
            skills: Cow::Borrowed(&[
                Cow::Borrowed("C++"),
                Cow::Borrowed("C"),
                Cow::Borrowed("Python"),
                Cow::Borrowed("Haskell"),
                Cow::Borrowed("Java"),
                Cow::Borrowed("Matlab"),
                Cow::Borrowed("VHDL"),
                Cow::Borrowed("ARM"),
                Cow::Borrowed("Rust"),
                Cow::Borrowed("Shell Scripting"),
                Cow::Borrowed("CMake"),
            ]),
        },
        SkillGroup {
            category: Cow::Borrowed("Libraries"),
            skills: Cow::Borrowed(&[
                Cow::Borrowed("OpenGL"),
                Cow::Borrowed("Vulkan"),
                Cow::Borrowed("Flask"),
            ]),
        },
        SkillGroup {
            category: Cow::Borrowed("Tools"),
            skills: Cow::Borrowed(&[
                Cow::Borrowed("Git"),
                Cow::Borrowed("Docker"),
                Cow::Borrowed("VS Code"),
                Cow::Borrowed("Visual Studio"),
                Cow::Borrowed("IntelliJ"),
                Cow::Borrowed("Jenkins"),
                Cow::Borrowed("MISRA"),
                Cow::Borrowed("PolySpace"),
            ]),
        },
        SkillGroup {
            category: Cow::Borrowed("Training/Certificates"),
            skills: Cow::Borrowed(&[
                Cow::Borrowed("DO-178C Certified"),
                Cow::Borrowed("C++ Training"),
            ]),
        },
        SkillGroup {
            category: Cow::Borrowed("Hobbies"),
            skills: Cow::Borrowed(&[
                Cow::Borrowed("Climbing"),
                Cow::Borrowed("Bouldering"),
                Cow::Borrowed("Leadership"),
                Cow::Borrowed("Drones"),
            ]),
        },
    ]),
};
