//! @generated by `sync-projects`; do not edit by hand.

use crate::projects::{Project, ProjectVisibility};

/// Selected projects generated from the configured GitHub repositories.
pub const PROJECTS: &[Project] = &[
    Project {
        id: "osdesa-atlas",
        repository: "osdesa/Atlas",
        title: "Atlas",
        summary: "Atlas is a modern C++ user-space scheduler for heterogeneous CPU/GPU work using Vulkan.",
        visibility: ProjectVisibility::Public,
        project_date: "2026-07-24",
        status: Some("Active"),
        technologies: &["C++", "Vulkan", "Catch2", "CMake", "Doxygen"],
        highlights: &[
            "Fully check task graph allowing custom tasks and dependencies to be created.",
            "Kahn schedular to provide simple baseline results",
        ],
        image_url: "/images/project-default.svg",
        repository_url: Some("https://github.com/osdesa/Atlas"),
        demo_url: None,
    },
    Project {
        id: "osdesa-personal-site",
        repository: "osdesa/personal-site",
        title: "Personal Website",
        summary: "A personal website that auto populates information from parsing CV and Github Repos",
        visibility: ProjectVisibility::Public,
        project_date: "2026-07-16",
        status: Some("Completed"),
        technologies: &["Rust", "Leptos", "WebAssembly", "GitHub Actions"],
        highlights: &[
            "Full auto parsing of CV pulled from Github Repo and auto populated into static webpage.",
            "Project based parsing of custom format for project info auto populated into website.",
            "Automated deployment of website to Cloudflare pages using Github Actions.",
            "Source of truth for project information is the CV and Github Repos, no need to manually update website.",
        ],
        image_url: "/images/projects/osdesa-personal-site.png",
        repository_url: Some("https://github.com/osdesa/personal-site"),
        demo_url: None,
    },
    Project {
        id: "osdesa-blocky",
        repository: "osdesa/Blocky",
        title: "Blocky",
        summary: "A voxel-based 3D game built in C++ with a custom OpenGL renderer, procedural terrain, dynamic sky rendering, and supporting mathematics infrastructure.",
        visibility: ProjectVisibility::Public,
        project_date: "2024-08-02",
        status: Some("Completed"),
        technologies: &["C++", "OpenGL", "GLSL", "GLFW", "FreeType", "FastNoiseLite"],
        highlights: &[
            "Built a chunk-based voxel world with procedurally generated terrain.",
            "Implemented custom rendering systems for textured blocks, water, and a dynamic sun and moon.",
            "Created reusable vector, matrix, collision, camera, shader, texture, and buffer abstractions.",
            "Developed an in-game user interface and text rendering system using FreeType.",
        ],
        image_url: "/images/projects/osdesa-blocky.png",
        repository_url: Some("https://github.com/osdesa/Blocky"),
        demo_url: Some("https://youtu.be/IdpWtqGbYhI"),
    },
];
