//! @generated by `sync-projects`; do not edit by hand.

use crate::projects::{Project, ProjectVisibility};

/// Selected projects generated from the configured GitHub repositories.
pub const PROJECTS: &[Project] = &[
    Project {
        id: "osdesa-personal-site",
        repository: "osdesa/personal-site",
        title: "Personal Website",
        summary: "A maintainable personal portfolio built in Rust with Leptos, generated CV and project data, and production-quality automation.",
        visibility: ProjectVisibility::Public,
        project_date: "2026-07-16",
        status: Some("Active"),
        technologies: &[
            "Rust",
            "Leptos",
            "WebAssembly",
            "Tailwind CSS",
            "GitHub Actions",
        ],
        highlights: &[
            "Typed build-time content generation keeps credentials and remote parsing out of the browser.",
            "Accessibility, deterministic tests, and release builds are enforced in continuous integration.",
        ],
        image_url: "/images/project-default.svg",
        repository_url: Some("https://github.com/osdesa/personal-site"),
        demo_url: None,
    },
    Project {
        id: "osdesa-blocky",
        repository: "osdesa/Blocky",
        title: "Blocky",
        summary: "A voxel-based 3D game built in C++ with a custom OpenGL renderer, procedural terrain, dynamic sky rendering, and supporting mathematics infrastructure.",
        visibility: ProjectVisibility::Public,
        project_date: "2024-08-02",
        status: Some("Completed"),
        technologies: &["C++", "OpenGL", "GLSL", "GLFW", "FreeType", "FastNoiseLite"],
        highlights: &[
            "Built a chunk-based voxel world with procedurally generated terrain.",
            "Implemented custom rendering systems for textured blocks, water, and a dynamic sun and moon.",
            "Created reusable vector, matrix, collision, camera, shader, texture, and buffer abstractions.",
            "Developed an in-game user interface and text rendering system using FreeType.",
        ],
        image_url: "/images/project-default.svg",
        repository_url: Some("https://github.com/osdesa/Blocky"),
        demo_url: Some("https://youtu.be/IdpWtqGbYhI"),
    },
];
