//! @generated by `sync-projects`; do not edit by hand.

use crate::projects::{Project, ProjectVisibility};

/// Selected projects generated from the configured GitHub repositories.
pub const PROJECTS: &[Project] = &[
    Project {
        id: "osdesa-atlas",
        repository: "osdesa/Atlas",
        title: "Atlas",
        summary: "Atlas is a tested C++20 task graph with concurrent CPU and Vulkan compute execution.",
        visibility: ProjectVisibility::Public,
        project_date: "2026-07-24",
        status: Some("Active"),
        technologies: &[
            "C++",
            "Vulkan SDK",
            "Catch2",
            "CMake",
            "ThreadSanitizer",
            "Doxygen",
        ],
        highlights: &[
            "Built directed acyclic task graphs with dependency validation and cycle rejection.",
            "Implemented capacity-aware Kahn scheduling through interchangeable synchronous and fixed-size worker-pool CPU executors.",
            "Built a compute-only Vulkan runtime with persistent buffers, pipelines, staging transfers, and declarative dispatches.",
            "Scheduled explicit CPU and GPU tasks through independent capacities and one shared attributed completion channel.",
            "Verified standalone and mixed compute through Mesa Lavapipe with checked GLSL-to-SPIR-V builds.",
            "Built a versioned reproducible benchmark runner with deterministic CPU/Vulkan DAGs and JSON Lines/CSV metrics.",
            "Compared direct and scheduled policy/slicing variants with paired deterministic confidence intervals.",
        ],
        image_url: "/images/project-default.svg",
        repository_url: Some("https://github.com/osdesa/Atlas"),
        demo_url: None,
    },
    Project {
        id: "osdesa-personal-site",
        repository: "osdesa/personal-site",
        title: "Personal Website",
        summary: "A personal website that auto populates information from parsing CV and Github Repos",
        visibility: ProjectVisibility::Public,
        project_date: "2026-07-16",
        status: Some("Completed"),
        technologies: &["Rust", "Leptos", "WebAssembly", "GitHub Actions"],
        highlights: &[
            "Full auto parsing of CV pulled from Github Repo and auto populated into static webpage.",
            "Project based parsing of custom format for project info auto populated into website.",
            "Automated deployment of website to Cloudflare pages using Github Actions.",
            "Source of truth for project information is the CV and Github Repos, no need to manually update website.",
        ],
        image_url: "/images/projects/osdesa-personal-site.png",
        repository_url: Some("https://github.com/osdesa/personal-site"),
        demo_url: None,
    },
    Project {
        id: "osdesa-blocky",
        repository: "osdesa/Blocky",
        title: "Blocky",
        summary: "A voxel-based 3D game built in C++ with a custom OpenGL renderer, procedural terrain, dynamic sky rendering, and supporting mathematics infrastructure.",
        visibility: ProjectVisibility::Public,
        project_date: "2024-08-02",
        status: Some("Completed"),
        technologies: &["C++", "OpenGL", "GLSL", "GLFW", "FreeType", "FastNoiseLite"],
        highlights: &[
            "Built a chunk-based voxel world with procedurally generated terrain.",
            "Implemented custom rendering systems for textured blocks, water, and a dynamic sun and moon.",
            "Created reusable vector, matrix, collision, camera, shader, texture, and buffer abstractions.",
            "Developed an in-game user interface and text rendering system using FreeType.",
        ],
        image_url: "/images/projects/osdesa-blocky.png",
        repository_url: Some("https://github.com/osdesa/Blocky"),
        demo_url: Some("https://youtu.be/IdpWtqGbYhI"),
    },
];
